In [3]:
import numpy as np
import keras

x = np.random.rand(1, 96, 96, 3)

layer = keras.layers.DepthwiseConv2D((3,3), depth_multiplier=4, activation='relu', padding="same")
y = layer(x)

print(layer.count_params())
# 120

print(y.shape)
# (1, 96, 96, 12)

120
(1, 96, 96, 12)


In [294]:
import numpy as np
import keras


In [315]:
x = np.random.rand(1, 96, 96, 3)
layer = keras.layers.DepthwiseConv2D((3,3), depth_multiplier=4, activation='relu', padding="same")
y = layer(x)

print(layer.count_params())
print(y.shape)

120
(1, 96, 96, 12)


In [317]:
from torch import nn

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

layer = nn.Conv2d(in_channels=3, out_channels=12, kernel_size=(3,3), groups=3)
print(count_parameters(layer))

120


In [314]:
import torch
from torch import nn

layer = nn.Conv2d(in_channels=2, out_channels=6, kernel_size=(1,1), groups=2)
weights, biases = list(layer.parameters())
input = torch.randn(1, 2, 1, 1)

display("======== Weights ========")
display(weights)

display("======== Biases ========")
display(biases)

display("======== Input ========")
display(input)

display("======== Output ========")

output = layer(input)
display(output)

'======== Weights ========'

Parameter containing:
tensor([[[[ 0.7041]]],


        [[[-0.5042]]],


        [[[ 0.1903]]],


        [[[-0.2888]]],


        [[[-0.7594]]],


        [[[-0.9167]]]], requires_grad=True)

'======== Biases ========'

Parameter containing:
tensor([-0.9765,  0.5035, -0.6238, -0.1216, -0.0423,  0.5719],
       requires_grad=True)

'======== Input ========'

tensor([[[[0.6636]],

         [[2.0137]]]])

'======== Output ========'

tensor([[[[-0.5093]],

         [[ 0.1689]],

         [[-0.4975]],

         [[-0.7032]],

         [[-1.5715]],

         [[-1.2741]]]], grad_fn=<ConvolutionBackward0>)

In [282]:
l1=(-0.6865)*(-1.6570)

l2= (0.3329)*(-0.0024)
b1= 0.7012


l3 = (0.6218)*(0.1792)
l4 = (-0.4560)*(-1.0504)

b2 = 0.3249

l3+l4+b2

0.91530896

In [249]:
def calc_default(w1, w2, b, in_1, in_2):
    return np.round((w1 * in_1) + (w2*in_2) +b, decimals=4)


print ("Calc Default Filter 1 (Layer 1 + Layer 2):")
w1 =-0.0886
w2 = 0.2835
b = -0.4439
in_1 = 2.3061
in_2 = 0.5617

print(calc_default(w1,w2,b,in_1,in_2))

print ("Calc Default Filter 2 (Layer 1 + Layer 2):")


Calc Default Filter 1 (Layer 1 + Layer 2):
-0.489
Calc Default Filter 2 (Layer 1 + Layer 2):


In [247]:
def calc_depth(weight, bias, in_val):
    return np.round(weight * in_val + bias, decimals=4)


print("Calc Depth Layer 1:")

w1 = -0.3735
b1 = -0.6408
in_1 = -1.5096

print(calc_depth(w1,b1,in_1))

print("Calc Depth Layer 2:")
w2 = 0.9717
b2 = -0.3645
in_2 = 0.4675

print(calc_depth(w2,b2,in_2))


Calc Depth Layer 1:
-0.077
Calc Depth Layer 2:
0.0898
